#!/usr/bin/env bash
rsync \
  --recursive \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --compress \
  --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
  ./css ./fonts ./img ./js ./lib ./plugin ./index.html \
  pixelastic:/var/www/pixelastic.com/talks.pixelastic.com/dist/memory-humantalks-2015



