#!/usr/bin/env bash
set -e

npm run build

rsync \
  --recursive \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --compress \
  ./public/* \
  pixelastic:/var/www/pixelastic.com/talks.pixelastic.com/slides/css-flags-mixit/

echo "Deployed on http://talks.pixelastic.com/slides/css-flags-mixit/"




